version: 2

sources:
  - name: coffee_shop
    description: '{{ doc( "doc_customers")}}'
    project: analytics-engineers-club
    freshness:
        error_after:
          count: 12
          period: hour
    loaded_at_field: created_at
    tables:
      - name: order_items
        columns: 
          - name: order_id
            tests: 
              - not_null
      
      - name: customers
        freshness:
          error_after:
            count: 12
            period: hour
        loaded_at_field: created_at
        columns:
          - name: id
            tests: 
              - unique
              - not_null
              
      - name: orders
        columns:
          - name: customer_id
            tests:
              - unique
              - not_null

      - name: products
        columns:
          - name: id
            tests:
              - unique
              - not_null

      - name: product_prices
        columns:
          - name: product_id
            tests:
              - unique
              - not_null